name: main

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Add key to allow access to repository
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo "${{ secrets.ACCESS_TOKEN }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cat <<EOT >> ~/.ssh/config
        Host github.com
        HostName github.com
        IdentityFile ~/.ssh/id_rsa
        EOT
    - name: Release to GitHub Pages
      env:
        USE_SSH: true
        GIT_USER: git
      run: |
        git config --global user.email "actions@gihub.com"
        git config --global user.name "gh-actions"
        yarn install
        yarn deploy
